import React from 'react';
import Head from 'next/head'
import { MainLayout, AboutPage } from '@components/index';
import { NextPageWithLayout } from '@typing';

const About: NextPageWithLayout = () => {
   return (
      <div>
         <Head>
            <title>Portfolio | About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <AboutPage />
      </div>
   );
};
About.Layout = MainLayout;
export default About;
