import React from 'react';
import Head from 'next/head'
import { MainLayout, AboutPage } from '@components/index';
import { NextPageWithLayout } from '@typing';
import { ThemeProps } from '@typing';
interface Props {
   theme?: ThemeProps;
}
const About: NextPageWithLayout = ({ theme }: Props) => {
   return (
      <div className="text-white">
         <Head>
            <title>Portfolio | About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <AboutPage theme={theme} />
      </div>
   );
};
About.Layout = MainLayout;
export default About;
