import React from 'react';
import Head from 'next/head';
import { MainLayout, AboutPage } from '@components/index';
import { DataFetching, NextPageWithLayout } from '@typing';
interface Props {
   data?: DataFetching;
}
const About: NextPageWithLayout = ({ data }: Props) => {
   return (
      <div>
         <Head>
            <title>Portfolio | About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <AboutPage infomation={data?.infomation}/>
      </div>
   );
};
About.Layout = MainLayout;
export default About;
