import { MainLayout, HomePage } from '@components/index'
import { NextPageWithLayout } from '@typing'

import Head from 'next/head'

const Home: NextPageWithLayout = () => {
  return (
    <div className="">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomePage />
    </div>
  )
}
Home.Layout = MainLayout
export default Home
