import MainLayout from '@components/Layout';
import { NextPageWithLayout, DataFetching } from '@typing';
import Head from 'next/head';
import React from 'react';
import { PortfolioPage } from '@components/index'
interface Props {
   data?: DataFetching
}
const Portfolio: NextPageWithLayout = ({data}: Props) => {
   return (
      <div>
         <Head>
            <title>Portfolio | Project</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <PortfolioPage project={data?.project}/>
      </div>
   );
};
Portfolio.Layout = MainLayout;
export default Portfolio;
